### ISSUE TITLE
Is IMU and camera of zed x one hardwared synchronized?

### ISSUE THREAD

**Issue by crowlongwings** [stereolabs/zedxone-ros2#3]
Hi,
From the  [spec](https://www.stereolabs.com/en-tr/store/products/zed-x-one) of ZED X ONE it seems that multiple ZED X ONE can be used with hardware synchronization. Are the IMU and the camera within a single ZED X ONE hardware synchronized as well? Is it possible to use a ZED X ONE module to implement a mono visual-inertial approach?
Thanks,

**Comment by Myzhar** [comment]
Yes, they are. You can use the timestamp to retrieve synchronization information.
I recommend using the new `stereolabs::ZedCameraOne` component of the [ZED ROS2 Wrapper](https://github.com/stereolabs/zed-ros2-wrapper)
