### ISSUE TITLE
The timestamp of zed One message is not sync with the system time

### ISSUE THREAD

**Issue by Alex-Beh** [stereolabs/zedxone-ros2#4]
when I ros2 topic echo the message, the timestamp are not sync to the system time.

![image](https://github.com/user-attachments/assets/1b6de608-d9c7-40b2-aaec-cbda47092790)

https://github.com/stereolabs/zedxone-ros2/blob/f3107e8c310768f0f5cce7713ba70b67f853b219/zedxone_components/src/zedxone_camera/src/zedxone_camera_component.cpp#L495

**Comment by muellerbernd** [comment]
I have exactly the same problem.

**Comment by Alex-Beh** [comment]
New ROS2 Zed X One wrapper https://github.com/stereolabs/zed-ros2-wrapper solved the issue.
